- name: "拷贝解压tomcat"
  unarchive: src=apache-tomcat-7.0.100.tar.gz dest=/usr/
- name: "重命名tomcat"  
  command: mv /usr/apache-tomcat-7.0.100 /usr/{{ tomcat_name }}
- name: templaste to server.xml
  template: src=server.xml dest=/usr/{{ tomcat_name }}/conf
- name: "copy to catalina.sh"
  copy: src=catalina.sh dest=/usr/{{ tomcat_name }}/bin
- name: "启动tomcat"
  command: nohup /usr/{{ tomcat_name }}/bin/startup.sh &
- name: "查看进程是否开启"
  shell: sleep 3;netstat -utpnl |grep {{ http_port }} |cat
  register: result
  tags: shell
- name: "显示是否开启端口"
  debug: var=result.stdout_lines
  tags: display

